# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Get package version
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Create a tag
        uses: negz/create-tag@v1
        with:
          version: v${{ steps.package-version.outputs.version }}
          message: 'Release v${{ steps.package-version.outputs.version }}'
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm npm install
      - run: npm run build
      - run: npm run build:types
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
